### ISSUE TITLE
Adding kde-next and build to pacman.conf breaks Wayland

### ISSUE THREAD

**Issue by madirishman** [KaOSx/core#15]
![screenshot_20170108_170413](https://cloud.githubusercontent.com/assets/22090937/21753934/87a41a8c-d5c4-11e6-9c1e-47b05ea8da4d.png) KaOS 2017.01. I can start a Wayland session from Live or an install without kde-next and build. When I add them this is what happens when I try to start Wayland: The desktop flashes twice then the screen goes to a working  three dots and a > image that I have heard called a Breeze Icon. Then after a few seconds the screen goes black. If I leave System Settings open before logging out from a Plasma session and logging in to a Wayland session it appears in the black screen as does the Xscreensaver settings screen, but there is no desktop. The default theme set after adding kde-next and build is Midna, so I thought it was the theme. A breeze workspace theme with oxygen desktop theme previously worked in Wayland, but not now.    The picture of InfoCenter was taken in a Plasma session, and the desktop theme shown in it is not what I used to try to start Wayland, I used Oxygen.

**Comment by demmm** [comment]
This is known ever since kde-next opened middle of December.
Not a core issue, so this one will be closed.  Feel free to re-open as an apps issue, probably needs an upstream fix in plasma-workspace.

Plasma fails to start any which calls for kde.org in their .desktop file.  If you have yakuake active, you still can run a wayland session by opening yakuake on your black screen (F12).  Then type `plasmashell`, in another tab type `krunner` and you will get a working wayland session again.
Do not try to open any Plasma app from the menu or shortcut, all starting from a .desktop with kde.org will fail.  Start dolphin for example from another tab in yakuake.
